In [1]:
!python -m pip install numpy

                                              0.0/15.0 MB ? eta -:--:--
                                              0.0/15.0 MB ? eta -:--:--
                                             0.0/15.0 MB 393.8 kB/s eta 0:00:39
                                             0.1/15.0 MB 819.2 kB/s eta 0:00:19
                                             0.1/15.0 MB 722.1 kB/s eta 0:00:21
                                             0.2/15.0 MB 888.4 kB/s eta 0:00:17
                                             0.2/15.0 MB 901.1 kB/s eta 0:00:17
                                             0.3/15.0 MB 874.6 kB/s eta 0:00:17
                                             0.3/15.0 MB 774.0 kB/s eta 0:00:20
                                             0.3/15.0 MB 791.9 kB/s eta 0:00:19
                                             0.3/15.0 MB 723.4 kB/s eta 0:00:21
                                             0.4/15.0 MB 742.3 kB/s eta 0:00:20
     -                                       0.4/15.0 MB


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: C:\Users\WELCOME\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [4]:
a=np.array([3,2,33,22,33])

In [5]:
type(a)

numpy.ndarray

In [6]:
print(a.shape)
print(a.size)
print(a.dtype)

(5,)
5
int32


In [4]:
def show_array(arr):
    print('Array:',arr,sep='\n')
    print('type:',type(arr))
    print('Shape:',arr.shape)
    print('size',arr.size)
    
    

In [7]:
import numpy as np


In [14]:
b=np.array([[[5,10],[6,10],[9,30],[5,20],[9,6],[90,9],[6,20],[6,60]]])

In [15]:
print(b)

[[[ 5 10]
  [ 6 10]
  [ 9 30]
  [ 5 20]
  [ 9  6]
  [90  9]
  [ 6 20]
  [ 6 60]]]


In [16]:
print(b.shape)

(1, 8, 2)


In [17]:
#subscripting [1st,2nd,3rd,.........nthdim]
#sunscripting [1st:1st end: stepsize,2nd , 3rd ,.......nth dim]
#slice maintain stucture
import numpy as np

In [19]:
c=np.array([[10,20,30,40],[20,6,0,222],[10,5,0,6]])

In [20]:
print(c)

[[ 10  20  30  40]
 [ 20   6   0 222]
 [ 10   5   0   6]]


In [22]:
c[2][0:]

array([10,  5,  0,  6])

In [28]:
d=np.array([[[10,100],[11,110],[13,130],[14,140]],[[45,145],[22,122],[9,19],[2,12]],[[6,16],[5,15],[1,11],[8,18]]])

In [30]:
print(d)

[[[ 10 100]
  [ 11 110]
  [ 13 130]
  [ 14 140]]

 [[ 45 145]
  [ 22 122]
  [  9  19]
  [  2  12]]

 [[  6  16]
  [  5  15]
  [  1  11]
  [  8  18]]]


In [27]:
d[0][1][1:]
d[1:]

array([[[ 45, 145],
        [ 22, 122],
        [  9,  19],
        [  2,  12]],

       [[ 23,   5],
        [ 22,  99],
        [ 33,  66],
        [ 88,  99]]])

In [31]:
print(d[:1,:2,:])

[[[ 10 100]
  [ 11 110]]]


In [32]:
d[:,1:2,:1]

array([[[11]],

       [[22]],

       [[ 5]]])

In [34]:
d[-2:,-1:,:1]

array([[[2]],

       [[8]]])

In [35]:
d[:2,-2:,:]

array([[[ 13, 130],
        [ 14, 140]],

       [[  9,  19],
        [  2,  12]]])

In [36]:
#item assingment
print(c)

[[ 10  20  30  40]
 [ 20   6   0 222]
 [ 10   5   0   6]]


In [38]:
c[1,1]=10

In [39]:
print(c)

[[ 10  20  30  40]
 [ 20  10   0 222]
 [ 10   5   0   6]]


In [41]:
#item insertion


In [42]:
a=np.array([10,2,2,00])

In [43]:
print(a)

[10  2  2  0]


In [44]:
np.append(a,80)

array([10,  2,  2,  0, 80])

In [47]:
print(d)

[[[ 10 100]
  [ 11 110]
  [ 13 130]
  [ 14 140]]

 [[ 45 145]
  [ 22 122]
  [  9  19]
  [  2  12]]

 [[  6  16]
  [  5  15]
  [  1  11]
  [  8  18]]]


In [51]:
#deleation
np.delete(a,0,axis=0)

array([2, 2, 0])

In [52]:
#airthmetic 


In [53]:
#numpy is different as list
a +20

array([30, 22, 22, 20])

In [54]:
a *a

array([100,   4,   4,   0])

In [57]:
#array mainupulation 
#more function to create array
a.reshape(2,1)

ValueError: cannot reshape array of size 4 into shape (2,1)

In [59]:
b.astype(float)

array([[[ 5., 10.],
        [ 6., 10.],
        [ 9., 30.],
        [ 5., 20.],
        [ 9.,  6.],
        [90.,  9.],
        [ 6., 20.],
        [ 6., 60.]]])